language: ruby

rvm:
- 2.4

script:
  - bundle exec rake test

exclude: [vendor]

# branch whitelist
branches:
  only:
  - master
  - develop

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

sudo: false  # route your build to the container-based infrastructure for a faster build
