language: ruby

dist: trusty

rvm:
  - 2.4

before_install:
  - sudo update-ca-certificates

before_script:
  - ruby -v
  - gem install jekyll
  - gem install bundler
  - bundle install

script:
  - bundle exec rake test

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# sudo: false # route your build to the container-based infrastructure for a faster build
sudo: required
