title: Simpl World
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    An open source platform for creating amazing games and simulations
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simple.world"
# url: "https://simple.world"
# enforce_ssl: "simple.world"
relative_permalinks: false
permalink: blog/:title/  # permalink: date

# Both of these settings may be removed after we are off the minima theme
twitter_username: simplworld
github_username: jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
exclude:
  - [vendor]
  - .editorconfig
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
include:
  - _pages

github: [metadata]

# SEO settings

twitter:
  username: simplworld
